"""10 Migration

Revision ID: 07a34631ee20
Revises: 3ea50e7ec6aa
Create Date: 2026-08-11 23:33:57.326052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a34631ee20'
down_revision: Union[str, Sequence[str], None] = '3ea50e7ec6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nuvemshop_integracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nuvemshop_integracoes_id'), 'nuvemshop_integracoes', ['id'], unique=False)
    op.create_index(op.f('ix_nuvemshop_integracoes_user_id'), 'nuvemshop_integracoes', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nuvemshop_integracoes_user_id'), table_name='nuvemshop_integracoes')
    op.drop_index(op.f('ix_nuvemshop_integracoes_id'), table_name='nuvemshop_integracoes')
    op.drop_table('nuvemshop_integracoes')
    # ### end Alembic commands ###
