"""Seven Migration

Revision ID: 42b1a4376bec
Revises: defc9fafeaa4
Create Date: 2026-08-02 20:54:42.969094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b1a4376bec'
down_revision: Union[str, Sequence[str], None] = 'defc9fafeaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro_custos', sa.Column('pertence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registro_custos', 'pertence')
    # ### end Alembic commands ###
