"""Second Migration

Revision ID: 5a086dda1b8a
Revises: b1c948ee73ef
Create Date: 2026-07-29 10:53:27.877791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a086dda1b8a'
down_revision: Union[str, Sequence[str], None] = 'b1c948ee73ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('estoque_cor_key'), 'estoque', type_='unique')
    op.drop_constraint(op.f('estoque_modelagem_key'), 'estoque', type_='unique')
    op.drop_constraint(op.f('estoque_tamanho_key'), 'estoque', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('estoque_tamanho_key'), 'estoque', ['tamanho'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('estoque_modelagem_key'), 'estoque', ['modelagem'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('estoque_cor_key'), 'estoque', ['cor'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
