"""Initial Migration

Revision ID: b1c948ee73ef
Revises: 
Create Date: 2026-07-28 23:03:16.357109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c948ee73ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_peca', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('tamanho', sa.String(), nullable=True),
    sa.Column('modelagem', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('preco_custo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cor'),
    sa.UniqueConstraint('modelagem'),
    sa.UniqueConstraint('sku'),
    sa.UniqueConstraint('tamanho')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimentacao', sa.String(), nullable=True),
    sa.Column('preco_custo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('estoque_anterior', sa.Integer(), nullable=True),
    sa.Column('estoque_depois', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_custos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('vencimento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_taxa', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_desconto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('frete', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('registro_custos')
    op.drop_table('movimentacoes_estoque')
    op.drop_table('usuarios')
    op.drop_table('estoque')
    # ### end Alembic commands ###
