"""Four Migration

Revision ID: c1c2720f4776
Revises: fdc2a61e074f
Create Date: 2026-08-01 18:56:45.193006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c2720f4776'
down_revision: Union[str, Sequence[str], None] = 'fdc2a61e074f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro_custos', sa.Column('aditional_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registro_custos', 'aditional_id')
    # ### end Alembic commands ###
