"""Ten Migration

Revision ID: d5a192d54643
Revises: eb748077139c
Create Date: 2026-08-08 11:01:24.155335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a192d54643'
down_revision: Union[str, Sequence[str], None] = 'eb748077139c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('taxaDesconto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('validade', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('estoque', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    op.add_column('estoque', sa.Column('estoqueInicial', sa.Integer(), nullable=True))
    op.add_column('estoque', sa.Column('restoque', sa.Integer(), nullable=True))
    op.add_column('estoque', sa.Column('vendas', sa.Integer(), nullable=True))
    op.add_column('estoque', sa.Column('estoqueAtual', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estoque', 'fornecedores', ['fornecedor_id'], ['id'])
    op.drop_column('estoque', 'estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.drop_column('estoque', 'estoqueAtual')
    op.drop_column('estoque', 'vendas')
    op.drop_column('estoque', 'restoque')
    op.drop_column('estoque', 'estoqueInicial')
    op.drop_column('estoque', 'fornecedor_id')
    op.drop_table('fornecedores')
    op.drop_table('cupons')
    # ### end Alembic commands ###
