"""Third Migration

Revision ID: fdc2a61e074f
Revises: 5a086dda1b8a
Create Date: 2026-08-01 10:38:45.448094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc2a61e074f'
down_revision: Union[str, Sequence[str], None] = '5a086dda1b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_drop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['drop_id'], ['drop.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('movimentacoes_estoque', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimentacoes_estoque', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimentacoes_estoque', type_='foreignkey')
    op.drop_column('movimentacoes_estoque', 'usuario_id')
    op.drop_table('item_drop')
    op.drop_table('drop')
    # ### end Alembic commands ###
